### ISSUE TITLE
Splitting to AI-Dev code + Dona-Dev code

### ISSUE THREAD

**Issue by AdityaMitra5102** [Gautam-Galada/DONA#3]
Required functions in AI-Dev code

- modelinit()
- train()
- test(data) #This function will also preprocess data like converting images to RGB or Grayscale tensors etc.
- datatype() #This function just returns what type of data the model will take for testing like "inages", "audio", "text". This will ensure what input donagram will take from telegram.

Functions in Dona-dev code will call the functions in AI-Dev Code and return output to telegram

**Comment by Gautam-Galada** [comment]
1. Added  Dona-dev and AI-Dev Code. Datatype : {pending.....} 
2. Code configuration and model spec is the problem for audio. 
3. Have to update the model spec and training pipeline 
4. Cuda information : narrow down. {in abundance}
5.  The hyper parameters have to be model oriented and asked in message after the data type is picked
6. Training has started -> Data Type -> hyperparameters (yes/no) -> training
